//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zigm.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zigm.Languages.AppLang", typeof(AppLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Zigm未管理任何本地Zig版本 的本地化字符串。
        /// </summary>
        public static string Zigm未管理本地版本 {
            get {
                return ResourceManager.GetString("Zigm未管理本地版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zigm管理的本地Zig版本: 的本地化字符串。
        /// </summary>
        public static string Zigm管理的本地Zig版本 {
            get {
                return ResourceManager.GetString("Zigm管理的本地Zig版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string 下载完成 {
            get {
                return ResourceManager.GetString("下载完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载超时: {0} {1} 的本地化字符串。
        /// </summary>
        public static string 下载超时 {
            get {
                return ResourceManager.GetString("下载超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持当前系统架构: {0} 的本地化字符串。
        /// </summary>
        public static string 不支持当前系统架构 {
            get {
                return ResourceManager.GetString("不支持当前系统架构", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从: {0} 的本地化字符串。
        /// </summary>
        public static string 从 {
            get {
                return ResourceManager.GetString("从", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用上下箭头键选择，按Enter键执行，按Esc键退出 的本地化字符串。
        /// </summary>
        public static string 使用上下箭头选择 {
            get {
                return ResourceManager.GetString("使用上下箭头选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string 保存配置文件失败 {
            get {
                return ResourceManager.GetString("保存配置文件失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改环境变量失败: {0} 的本地化字符串。
        /// </summary>
        public static string 修改环境变量失败 {
            get {
                return ResourceManager.GetString("修改环境变量失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改系统环境变量需要管理员权限，请以管理员身份运行程序。 的本地化字符串。
        /// </summary>
        public static string 修改系统环境变量需要管理员权限 {
            get {
                return ResourceManager.GetString("修改系统环境变量需要管理员权限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共安装了 {0} 个版本 的本地化字符串。
        /// </summary>
        public static string 共安装了版本 {
            get {
                return ResourceManager.GetString("共安装了版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共找到 {0} 个版本 的本地化字符串。
        /// </summary>
        public static string 共找到版本 {
            get {
                return ResourceManager.GetString("共找到版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到版本 {0} 失败，环境变量更新失败 的本地化字符串。
        /// </summary>
        public static string 切换到版本失败 {
            get {
                return ResourceManager.GetString("切换到版本失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换版本 的本地化字符串。
        /// </summary>
        public static string 切换版本 {
            get {
                return ResourceManager.GetString("切换版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列出所有可用的Zig版本... 的本地化字符串。
        /// </summary>
        public static string 列出可用版本 {
            get {
                return ResourceManager.GetString("列出可用版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列出本地已安装的Zig版本... 的本地化字符串。
        /// </summary>
        public static string 列出本地版本 {
            get {
                return ResourceManager.GetString("列出本地版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到: {0} 的本地化字符串。
        /// </summary>
        public static string 到 {
            get {
                return ResourceManager.GetString("到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载配置文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string 加载配置文件失败 {
            get {
                return ResourceManager.GetString("加载配置文件失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载Zig版本 的本地化字符串。
        /// </summary>
        public static string 卸载Zig版本 {
            get {
                return ResourceManager.GetString("卸载Zig版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载版本 的本地化字符串。
        /// </summary>
        public static string 卸载版本 {
            get {
                return ResourceManager.GetString("卸载版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用的版本： 的本地化字符串。
        /// </summary>
        public static string 可用的版本 {
            get {
                return ResourceManager.GetString("可用的版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用的Zig稳定版本: 的本地化字符串。
        /// </summary>
        public static string 可用稳定版本 {
            get {
                return ResourceManager.GetString("可用稳定版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可选参数: --system (系统级安装，需要管理员权限) 的本地化字符串。
        /// </summary>
        public static string 可选参数系统级 {
            get {
                return ResourceManager.GetString("可选参数系统级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zig 版本管理器 的本地化字符串。
        /// </summary>
        public static string 名称 {
            get {
                return ResourceManager.GetString("名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动交互式界面... 的本地化字符串。
        /// </summary>
        public static string 启动交互式界面 {
            get {
                return ResourceManager.GetString("启动交互式界面", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在Linux, MacOS, BSD上设置PATH: 的本地化字符串。
        /// </summary>
        public static string 在LinuxMacOSBSD上设置PATH {
            get {
                return ResourceManager.GetString("在LinuxMacOSBSD上设置PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在Windows上设置PATH: 的本地化字符串。
        /// </summary>
        public static string 在Windows上设置PATH {
            get {
                return ResourceManager.GetString("在Windows上设置PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储路径: {0} 的本地化字符串。
        /// </summary>
        public static string 存储路径 {
            get {
                return ResourceManager.GetString("存储路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装Zig版本 的本地化字符串。
        /// </summary>
        public static string 安装Zig版本 {
            get {
                return ResourceManager.GetString("安装Zig版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装新版本 的本地化字符串。
        /// </summary>
        public static string 安装新版本 {
            get {
                return ResourceManager.GetString("安装新版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成后，请重新加载你的启动文件（例如: source ~/.profile 或 source ~/.zshrc）或者重启Shell。 的本地化字符串。
        /// </summary>
        public static string 完成后请重新加载启动文件或重启Shell {
            get {
                return ResourceManager.GetString("完成后请重新加载启动文件或重启Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官方PATH设置建议: 的本地化字符串。
        /// </summary>
        public static string 官方PATH设置建议 {
            get {
                return ResourceManager.GetString("官方PATH设置建议", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将zig二进制镜像的位置添加到PATH环境变量中。 的本地化字符串。
        /// </summary>
        public static string 将zig二进制镜像的位置添加到PATH环境变量中 {
            get {
                return ResourceManager.GetString("将zig二进制镜像的位置添加到PATH环境变量中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将使用默认配置 的本地化字符串。
        /// </summary>
        public static string 将使用默认配置 {
            get {
                return ResourceManager.GetString("将使用默认配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已安装: 否 的本地化字符串。
        /// </summary>
        public static string 已安装否 {
            get {
                return ResourceManager.GetString("已安装否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已安装: 是 的本地化字符串。
        /// </summary>
        public static string 已安装是 {
            get {
                return ResourceManager.GetString("已安装是", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已将Zig {0} 添加到系统PATH中 的本地化字符串。
        /// </summary>
        public static string 已将Zig添加到PATH中 {
            get {
                return ResourceManager.GetString("已将Zig添加到PATH中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已将Zig {0} {1}添加到系统PATH中 的本地化字符串。
        /// </summary>
        public static string 已将Zig添加到系统PATH中 {
            get {
                return ResourceManager.GetString("已将Zig添加到系统PATH中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已将版本 {0} 设置为当前版本 的本地化字符串。
        /// </summary>
        public static string 已将版本设置为当前版本 {
            get {
                return ResourceManager.GetString("已将版本设置为当前版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功切换到版本 {0} 的本地化字符串。
        /// </summary>
        public static string 已成功切换到版本 {
            get {
                return ResourceManager.GetString("已成功切换到版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zigm 的本地化字符串。
        /// </summary>
        public static string 应用名称 {
            get {
                return ResourceManager.GetString("应用名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前使用的Zig版本: {0} 的本地化字符串。
        /// </summary>
        public static string 当前使用版本 {
            get {
                return ResourceManager.GetString("当前使用版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本 的本地化字符串。
        /// </summary>
        public static string 当前版本 {
            get {
                return ResourceManager.GetString("当前版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: {0} 的本地化字符串。
        /// </summary>
        public static string 当前版本配置 {
            get {
                return ResourceManager.GetString("当前版本配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到Zig可执行文件: {0} 的本地化字符串。
        /// </summary>
        public static string 找不到Zig可执行文件 {
            get {
                return ResourceManager.GetString("找不到Zig可执行文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到指定版本: {0} 的本地化字符串。
        /// </summary>
        public static string 找不到指定版本 {
            get {
                return ResourceManager.GetString("找不到指定版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键返回主菜单... 的本地化字符串。
        /// </summary>
        public static string 按任意键返回主菜单 {
            get {
                return ResourceManager.GetString("按任意键返回主菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键退出... 的本地化字符串。
        /// </summary>
        public static string 按任意键退出 {
            get {
                return ResourceManager.GetString("按任意键退出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的config命令用法 的本地化字符串。
        /// </summary>
        public static string 无效的config命令用法 {
            get {
                return ResourceManager.GetString("无效的config命令用法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的下载链接: {0} 的本地化字符串。
        /// </summary>
        public static string 无效的下载链接 {
            get {
                return ResourceManager.GetString("无效的下载链接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的选择 的本地化字符串。
        /// </summary>
        public static string 无效的选择 {
            get {
                return ResourceManager.GetString("无效的选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前使用的Zig版本... 的本地化字符串。
        /// </summary>
        public static string 显示当前版本 {
            get {
                return ResourceManager.GetString("显示当前版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前配置 的本地化字符串。
        /// </summary>
        public static string 显示当前配置 {
            get {
                return ResourceManager.GetString("显示当前配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新Zigm到最新版本... 的本地化字符串。
        /// </summary>
        public static string 更新到最新版本 {
            get {
                return ResourceManager.GetString("更新到最新版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新配置项 {0} 失败: {1} 的本地化字符串。
        /// </summary>
        public static string 更新配置项失败 {
            get {
                return ResourceManager.GetString("更新配置项失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的配置项: {0} 的本地化字符串。
        /// </summary>
        public static string 未知的配置项 {
            get {
                return ResourceManager.GetString("未知的配置项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知选项 的本地化字符串。
        /// </summary>
        public static string 未知选项 {
            get {
                return ResourceManager.GetString("未知选项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zigm未管理任何本地Zig版本 的本地化字符串。
        /// </summary>
        public static string 未管理任何版本 {
            get {
                return ResourceManager.GetString("未管理任何版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能获取到可用的Zig版本信息，请检查网络连接 的本地化字符串。
        /// </summary>
        public static string 未获取到版本 {
            get {
                return ResourceManager.GetString("未获取到版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置 的本地化字符串。
        /// </summary>
        public static string 未设置 {
            get {
                return ResourceManager.GetString("未设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置当前使用的Zig版本 的本地化字符串。
        /// </summary>
        public static string 未设置当前版本 {
            get {
                return ResourceManager.GetString("未设置当前版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地未安装任何Zig版本，无法切换 的本地化字符串。
        /// </summary>
        public static string 本地未安装任何版本 {
            get {
                return ResourceManager.GetString("本地未安装任何版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地未安装任何Zig版本，无法卸载 的本地化字符串。
        /// </summary>
        public static string 本地未安装任何版本无法卸载 {
            get {
                return ResourceManager.GetString("本地未安装任何版本无法卸载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看可用Zig版本 的本地化字符串。
        /// </summary>
        public static string 查看可用版本 {
            get {
                return ResourceManager.GetString("查看可用版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看本地已安装版本 的本地化字符串。
        /// </summary>
        public static string 查看已安装版本 {
            get {
                return ResourceManager.GetString("查看已安装版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载: {0} 的本地化字符串。
        /// </summary>
        public static string 正在下载 {
            get {
                return ResourceManager.GetString("正在下载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装版本: {0} 的本地化字符串。
        /// </summary>
        public static string 正在安装版本 {
            get {
                return ResourceManager.GetString("正在安装版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本: {0} 的本地化字符串。
        /// </summary>
        public static string 版本 {
            get {
                return ResourceManager.GetString("版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 卸载失败 的本地化字符串。
        /// </summary>
        public static string 版本卸载失败 {
            get {
                return ResourceManager.GetString("版本卸载失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 卸载成功 的本地化字符串。
        /// </summary>
        public static string 版本卸载成功 {
            get {
                return ResourceManager.GetString("版本卸载成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号不能为空 的本地化字符串。
        /// </summary>
        public static string 版本号不能为空 {
            get {
                return ResourceManager.GetString("版本号不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 安装失败 的本地化字符串。
        /// </summary>
        public static string 版本安装失败 {
            get {
                return ResourceManager.GetString("版本安装失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 安装成功 的本地化字符串。
        /// </summary>
        public static string 版本安装成功 {
            get {
                return ResourceManager.GetString("版本安装成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 是当前使用的版本，无法卸载 的本地化字符串。
        /// </summary>
        public static string 版本是当前使用的版本无法卸载 {
            get {
                return ResourceManager.GetString("版本是当前使用的版本无法卸载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 未安装 的本地化字符串。
        /// </summary>
        public static string 版本未安装 {
            get {
                return ResourceManager.GetString("版本未安装", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 环境变量已刷新 的本地化字符串。
        /// </summary>
        public static string 环境变量已刷新 {
            get {
                return ResourceManager.GetString("环境变量已刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户级安装 (PowerShell): 的本地化字符串。
        /// </summary>
        public static string 用户级安装PowerShell {
            get {
                return ResourceManager.GetString("用户级安装PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用法： 的本地化字符串。
        /// </summary>
        public static string 用法 {
            get {
                return ResourceManager.GetString("用法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string 秒 {
            get {
                return ResourceManager.GetString("秒", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统中已安装的Zig信息: 的本地化字符串。
        /// </summary>
        public static string 系统已安装信息 {
            get {
                return ResourceManager.GetString("系统已安装信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统级安装 (管理员 PowerShell): 的本地化字符串。
        /// </summary>
        public static string 系统级安装管理员PowerShell {
            get {
                return ResourceManager.GetString("系统级安装管理员PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统默认 的本地化字符串。
        /// </summary>
        public static string 系统默认 {
            get {
                return ResourceManager.GetString("系统默认", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检查更新: {0} 的本地化字符串。
        /// </summary>
        public static string 自动检查更新 {
            get {
                return ResourceManager.GetString("自动检查更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在获取版本信息，请稍候... 的本地化字符串。
        /// </summary>
        public static string 获取版本信息 {
            get {
                return ResourceManager.GetString("获取版本信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要在Windows上设置PATH，请在PowerShell中运行以下任一代码片段: 的本地化字符串。
        /// </summary>
        public static string 要在Windows上设置PATH请在PowerShell中运行以下任一代码片段 {
            get {
                return ResourceManager.GetString("要在Windows上设置PATH请在PowerShell中运行以下任一代码片段", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置配置项 的本地化字符串。
        /// </summary>
        public static string 设置配置项 {
            get {
                return ResourceManager.GetString("设置配置项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置: {0} 的本地化字符串。
        /// </summary>
        public static string 语言设置 {
            get {
                return ResourceManager.GetString("语言设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定要使用的Zig版本，例如: zigm use 0.11.0 的本地化字符串。
        /// </summary>
        public static string 请指定使用版本 {
            get {
                return ResourceManager.GetString("请指定使用版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定要卸载的Zig版本，例如: zigm uninstall 0.10.0 的本地化字符串。
        /// </summary>
        public static string 请指定卸载版本 {
            get {
                return ResourceManager.GetString("请指定卸载版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定要安装的Zig版本，例如: zigm install 0.12.0 的本地化字符串。
        /// </summary>
        public static string 请指定安装版本 {
            get {
                return ResourceManager.GetString("请指定安装版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入要安装的版本号（例如：0.12.0）:  的本地化字符串。
        /// </summary>
        public static string 请输入要安装的版本号 {
            get {
                return ResourceManager.GetString("请输入要安装的版本号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择操作： 的本地化字符串。
        /// </summary>
        public static string 请选择操作 {
            get {
                return ResourceManager.GetString("请选择操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要切换的版本序号:  的本地化字符串。
        /// </summary>
        public static string 请选择要切换的版本序号 {
            get {
                return ResourceManager.GetString("请选择要切换的版本序号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要卸载的版本序号:  的本地化字符串。
        /// </summary>
        public static string 请选择要卸载的版本序号 {
            get {
                return ResourceManager.GetString("请选择要卸载的版本序号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径: {0} 的本地化字符串。
        /// </summary>
        public static string 路径 {
            get {
                return ResourceManager.GetString("路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行完毕后请重启你的PowerShell实例。 的本地化字符串。
        /// </summary>
        public static string 运行完毕后重启PowerShell实例 {
            get {
                return ResourceManager.GetString("运行完毕后重启PowerShell实例", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这通常通过将export行添加到你的shell启动脚本 (.profile, .zshrc, ...) 的本地化字符串。
        /// </summary>
        public static string 这通常通过将export行添加到你的shell启动脚本 {
            get {
                return ResourceManager.GetString("这通常通过将export行添加到你的shell启动脚本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string 退出 {
            get {
                return ResourceManager.GetString("退出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置项 {0} 已更新为 {1} 的本地化字符串。
        /// </summary>
        public static string 配置项已更新 {
            get {
                return ResourceManager.GetString("配置项已更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置配置为默认值 的本地化字符串。
        /// </summary>
        public static string 重置配置为默认值 {
            get {
                return ResourceManager.GetString("重置配置为默认值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string 默认 {
            get {
                return ResourceManager.GetString("默认", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认源: {0} 的本地化字符串。
        /// </summary>
        public static string 默认源 {
            get {
                return ResourceManager.GetString("默认源", resourceCulture);
            }
        }
    }
}
